### ISSUE TITLE
Malformed update json

### ISSUE THREAD

**Issue by ChiefArug** [mactso/HarderMonsterBoats#1]
```
[Forge Version Check/INFO]: [hardermonsterboats] Starting version check at https://github.com/mactso/HarderMonsterBoats/raw/main/update.json
[Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.2.0.jar%231226!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.2.0.jar%231226!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23121!/:?]
	... 6 more
```
Nothing crash worthy, just an uneeded stacktrace in the logs

**Comment by mactso** [comment]
I'll fix this today.  Sorry I missed this!

I'll keep it open until it's fixed.

**Comment by mactso** [comment]
For some reason I'm having trouble fixing this.   Going to show it to my bud.  I'm probably missing something obvious.

**Comment by mactso** [comment]
Pretty sure I fixed this but forgot to close the issue.

Thanks for your bug report!  They help.

With Best Regards,
Two Guys,
MacTso
